name: Deploy Frontend

on:
  push:
    branches:
      - Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Construir imagen Docker
        run: docker build -t proyecto-frontend .

      - name: Pipeline completado
        run: echo "Deploy Frontend ejecutado correctamente"
